"""
Setup Community Subjects - Seed data for StudyHub marketplace
Creates standardized subject topics that creators can publish courses to

Run: python setup_community_subjects.py
"""

from src.database.db_manager import DBManager
from datetime import datetime
import logging

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


COMMUNITY_SUBJECTS = [
    # ==================== IT CATEGORY ====================
    {
        "_id": "python-programming",
        "slug": "python-programming",
        "title": "Python Programming",
        "title_vi": "Lập trình Python",
        "description": "Learn Python programming from basics to advanced concepts",
        "description_vi": "Học lập trình Python từ cơ bản đến nâng cao",
        "category": "it",
        "icon": "🐍",
        "keywords": ["python", "programming", "coding", "software"],
        "meta_description": "Master Python programming with courses from expert instructors",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": True,
        "display_order": 1,
    },
    {
        "_id": "javascript-programming",
        "slug": "javascript-programming",
        "title": "JavaScript Programming",
        "title_vi": "Lập trình JavaScript",
        "description": "Master JavaScript from fundamentals to advanced frameworks",
        "description_vi": "Làm chủ JavaScript từ cơ bản đến framework nâng cao",
        "category": "it",
        "icon": "📜",
        "keywords": ["javascript", "js", "web", "frontend"],
        "meta_description": "Learn JavaScript programming and web development",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": True,
        "display_order": 2,
    },
    {
        "_id": "react-development",
        "slug": "react-development",
        "title": "React Development",
        "title_vi": "Phát triển React",
        "description": "Build modern web applications with React",
        "description_vi": "Xây dựng ứng dụng web hiện đại với React",
        "category": "it",
        "icon": "⚛️",
        "keywords": ["react", "reactjs", "frontend", "ui"],
        "meta_description": "Master React development and build scalable applications",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": True,
        "display_order": 3,
    },
    {
        "_id": "nodejs-development",
        "slug": "nodejs-development",
        "title": "Node.js Development",
        "title_vi": "Phát triển Node.js",
        "description": "Server-side JavaScript with Node.js",
        "description_vi": "JavaScript phía server với Node.js",
        "category": "it",
        "icon": "🟢",
        "keywords": ["nodejs", "backend", "server", "api"],
        "meta_description": "Learn Node.js backend development",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 4,
    },
    {
        "_id": "web-development",
        "slug": "web-development",
        "title": "Web Development",
        "title_vi": "Phát triển Web",
        "description": "Full stack web development from HTML to deployment",
        "description_vi": "Phát triển web full stack từ HTML đến triển khai",
        "category": "it",
        "icon": "🌐",
        "keywords": ["web", "html", "css", "fullstack"],
        "meta_description": "Complete web development courses",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": True,
        "display_order": 5,
    },
    {
        "_id": "data-science",
        "slug": "data-science",
        "title": "Data Science",
        "title_vi": "Khoa học Dữ liệu",
        "description": "Data analysis, machine learning, and AI",
        "description_vi": "Phân tích dữ liệu, machine learning và AI",
        "category": "it",
        "icon": "📊",
        "keywords": ["data", "science", "ml", "ai", "analytics"],
        "meta_description": "Master data science and machine learning",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": True,
        "display_order": 6,
    },
    {
        "_id": "mobile-app-development",
        "slug": "mobile-app-development",
        "title": "Mobile App Development",
        "title_vi": "Phát triển Ứng dụng Di động",
        "description": "Build iOS and Android applications",
        "description_vi": "Xây dựng ứng dụng iOS và Android",
        "category": "it",
        "icon": "📱",
        "keywords": ["mobile", "ios", "android", "app"],
        "meta_description": "Learn mobile app development",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 7,
    },
    {
        "_id": "database-design",
        "slug": "database-design",
        "title": "Database Design",
        "title_vi": "Thiết kế Cơ sở Dữ liệu",
        "description": "SQL, NoSQL, and database architecture",
        "description_vi": "SQL, NoSQL và kiến trúc cơ sở dữ liệu",
        "category": "it",
        "icon": "🗄️",
        "keywords": ["database", "sql", "nosql", "mongodb"],
        "meta_description": "Master database design and management",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 8,
    },
    # ==================== BUSINESS CATEGORY ====================
    {
        "_id": "marketing-fundamentals",
        "slug": "marketing-fundamentals",
        "title": "Marketing Fundamentals",
        "title_vi": "Cơ bản Marketing",
        "description": "Essential marketing concepts and strategies",
        "description_vi": "Các khái niệm và chiến lược marketing cơ bản",
        "category": "business",
        "icon": "📊",
        "keywords": ["marketing", "business", "strategy"],
        "meta_description": "Learn marketing fundamentals",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": True,
        "display_order": 1,
    },
    {
        "_id": "digital-marketing",
        "slug": "digital-marketing",
        "title": "Digital Marketing",
        "title_vi": "Marketing Số",
        "description": "Online marketing, SEO, social media, and ads",
        "description_vi": "Marketing online, SEO, mạng xã hội và quảng cáo",
        "category": "business",
        "icon": "💻",
        "keywords": ["digital", "marketing", "seo", "social"],
        "meta_description": "Master digital marketing strategies",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": True,
        "display_order": 2,
    },
    {
        "_id": "entrepreneurship",
        "slug": "entrepreneurship",
        "title": "Entrepreneurship",
        "title_vi": "Khởi nghiệp",
        "description": "Start and grow your own business",
        "description_vi": "Khởi nghiệp và phát triển doanh nghiệp",
        "category": "business",
        "icon": "🚀",
        "keywords": ["startup", "entrepreneur", "business"],
        "meta_description": "Learn how to start your own business",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": True,
        "display_order": 3,
    },
    {
        "_id": "financial-management",
        "slug": "financial-management",
        "title": "Financial Management",
        "title_vi": "Quản lý Tài chính",
        "description": "Personal and business finance",
        "description_vi": "Tài chính cá nhân và doanh nghiệp",
        "category": "business",
        "icon": "💰",
        "keywords": ["finance", "accounting", "money"],
        "meta_description": "Master financial management",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 4,
    },
    {
        "_id": "project-management",
        "slug": "project-management",
        "title": "Project Management",
        "title_vi": "Quản lý Dự án",
        "description": "Plan, execute, and deliver successful projects",
        "description_vi": "Lập kế hoạch, thực hiện và giao dự án thành công",
        "category": "business",
        "icon": "📋",
        "keywords": ["project", "management", "agile", "scrum"],
        "meta_description": "Learn project management skills",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 5,
    },
    # ==================== ACADEMICS CATEGORY ====================
    {
        "_id": "toan-12",
        "slug": "toan-12",
        "title": "Toán 12",
        "title_vi": "Toán học lớp 12",
        "description": "Mathematics for Grade 12 - Vietnam curriculum",
        "description_vi": "Toán học lớp 12 theo chương trình Việt Nam",
        "category": "academics",
        "icon": "📐",
        "keywords": ["toán", "math", "grade12", "học"],
        "meta_description": "Học Toán 12 theo chương trình chuẩn",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": True,
        "display_order": 1,
    },
    {
        "_id": "vat-ly-12",
        "slug": "vat-ly-12",
        "title": "Vật lý 12",
        "title_vi": "Vật lý lớp 12",
        "description": "Physics for Grade 12 - Vietnam curriculum",
        "description_vi": "Vật lý lớp 12 theo chương trình Việt Nam",
        "category": "academics",
        "icon": "⚗️",
        "keywords": ["vật lý", "physics", "grade12"],
        "meta_description": "Học Vật lý 12 theo chương trình chuẩn",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": True,
        "display_order": 2,
    },
    {
        "_id": "hoa-hoc-12",
        "slug": "hoa-hoc-12",
        "title": "Hóa học 12",
        "title_vi": "Hóa học lớp 12",
        "description": "Chemistry for Grade 12 - Vietnam curriculum",
        "description_vi": "Hóa học lớp 12 theo chương trình Việt Nam",
        "category": "academics",
        "icon": "🧪",
        "keywords": ["hóa", "chemistry", "grade12"],
        "meta_description": "Học Hóa học 12 theo chương trình chuẩn",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": True,
        "display_order": 3,
    },
    {
        "_id": "tieng-anh-12",
        "slug": "tieng-anh-12",
        "title": "Tiếng Anh 12",
        "title_vi": "Tiếng Anh lớp 12",
        "description": "English for Grade 12 - Vietnam curriculum",
        "description_vi": "Tiếng Anh lớp 12 theo chương trình Việt Nam",
        "category": "academics",
        "icon": "🇬🇧",
        "keywords": ["english", "tiếng anh", "grade12"],
        "meta_description": "Học Tiếng Anh 12 theo chương trình chuẩn",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": True,
        "display_order": 4,
    },
    {
        "_id": "ielts-preparation",
        "slug": "ielts-preparation",
        "title": "IELTS Preparation",
        "title_vi": "Luyện thi IELTS",
        "description": "Prepare for IELTS exam - all skills",
        "description_vi": "Luyện thi IELTS - tất cả kỹ năng",
        "category": "academics",
        "icon": "📚",
        "keywords": ["ielts", "english", "test", "exam"],
        "meta_description": "Complete IELTS preparation courses",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": True,
        "display_order": 5,
    },
    {
        "_id": "toeic-preparation",
        "slug": "toeic-preparation",
        "title": "TOEIC Preparation",
        "title_vi": "Luyện thi TOEIC",
        "description": "Prepare for TOEIC exam",
        "description_vi": "Luyện thi TOEIC",
        "category": "academics",
        "icon": "📝",
        "keywords": ["toeic", "english", "test"],
        "meta_description": "TOEIC preparation and practice",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 6,
    },
    # ==================== LANGUAGE CATEGORY ====================
    {
        "_id": "english-speaking",
        "slug": "english-speaking",
        "title": "English Speaking",
        "title_vi": "Giao tiếp Tiếng Anh",
        "description": "Improve your English speaking and conversation skills",
        "description_vi": "Cải thiện kỹ năng nói và giao tiếp Tiếng Anh",
        "category": "language",
        "icon": "🗣️",
        "keywords": ["english", "speaking", "conversation"],
        "meta_description": "Master English speaking skills",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": True,
        "display_order": 1,
    },
    {
        "_id": "chinese-language",
        "slug": "chinese-language",
        "title": "Chinese Language",
        "title_vi": "Tiếng Trung",
        "description": "Learn Mandarin Chinese from basics to advanced",
        "description_vi": "Học Tiếng Trung từ cơ bản đến nâng cao",
        "category": "language",
        "icon": "🇨🇳",
        "keywords": ["chinese", "mandarin", "中文"],
        "meta_description": "Learn Chinese language",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": True,
        "display_order": 2,
    },
    {
        "_id": "japanese-language",
        "slug": "japanese-language",
        "title": "Japanese Language",
        "title_vi": "Tiếng Nhật",
        "description": "Learn Japanese from basics to JLPT",
        "description_vi": "Học Tiếng Nhật từ cơ bản đến JLPT",
        "category": "language",
        "icon": "🇯🇵",
        "keywords": ["japanese", "日本語", "jlpt"],
        "meta_description": "Learn Japanese language and culture",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": True,
        "display_order": 3,
    },
    {
        "_id": "korean-language",
        "slug": "korean-language",
        "title": "Korean Language",
        "title_vi": "Tiếng Hàn",
        "description": "Learn Korean from basics to TOPIK",
        "description_vi": "Học Tiếng Hàn từ cơ bản đến TOPIK",
        "category": "language",
        "icon": "🇰🇷",
        "keywords": ["korean", "한국어", "topik"],
        "meta_description": "Learn Korean language and culture",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 4,
    },
    # ==================== DESIGN CATEGORY ====================
    {
        "_id": "graphic-design",
        "slug": "graphic-design",
        "title": "Graphic Design",
        "title_vi": "Thiết kế Đồ họa",
        "description": "Master graphic design with Photoshop, Illustrator",
        "description_vi": "Làm chủ thiết kế đồ họa với Photoshop, Illustrator",
        "category": "design",
        "icon": "🎨",
        "keywords": ["design", "graphic", "photoshop"],
        "meta_description": "Learn graphic design skills",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": True,
        "display_order": 1,
    },
    {
        "_id": "ui-ux-design",
        "slug": "ui-ux-design",
        "title": "UI/UX Design",
        "title_vi": "Thiết kế UI/UX",
        "description": "User interface and user experience design",
        "description_vi": "Thiết kế giao diện và trải nghiệm người dùng",
        "category": "design",
        "icon": "📱",
        "keywords": ["ui", "ux", "design", "figma"],
        "meta_description": "Master UI/UX design",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": True,
        "display_order": 2,
    },
    {
        "_id": "video-editing",
        "slug": "video-editing",
        "title": "Video Editing",
        "title_vi": "Dựng Video",
        "description": "Professional video editing with Premiere, After Effects",
        "description_vi": "Dựng video chuyên nghiệp với Premiere, After Effects",
        "category": "design",
        "icon": "🎬",
        "keywords": ["video", "editing", "premiere"],
        "meta_description": "Learn video editing and production",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": True,
        "display_order": 3,
    },
]


def setup_community_subjects():
    """Seed community subjects collection"""
    try:
        db_manager = DBManager()
        db = db_manager.db
        collection = db["community_subjects"]

        # Add timestamps
        now = datetime.utcnow()
        for subject in COMMUNITY_SUBJECTS:
            subject["created_at"] = now
            subject["updated_at"] = now

        # Drop existing collection (if re-seeding)
        # collection.drop()
        # logger.info("Dropped existing community_subjects collection")

        # Insert subjects
        result = collection.insert_many(COMMUNITY_SUBJECTS)
        logger.info(f"✅ Inserted {len(result.inserted_ids)} community subjects")

        # Create indexes
        logger.info("Creating indexes...")
        collection.create_index([("slug", 1)], unique=True)
        collection.create_index([("category", 1)])
        collection.create_index([("title", "text"), ("title_vi", "text")])
        collection.create_index([("total_courses", -1)])
        collection.create_index([("total_students", -1)])
        collection.create_index([("is_featured", -1), ("display_order", 1)])
        logger.info("✅ Created indexes for community_subjects")

        # Print summary
        logger.info("\n" + "=" * 60)
        logger.info("SUMMARY BY CATEGORY:")
        logger.info("=" * 60)
        for category in ["it", "business", "academics", "language", "design"]:
            count = len([s for s in COMMUNITY_SUBJECTS if s["category"] == category])
            logger.info(f"  {category.upper()}: {count} subjects")

        logger.info("\n✅ Community subjects setup completed!")
        logger.info(f"Total subjects: {len(COMMUNITY_SUBJECTS)}")

    except Exception as e:
        logger.error(f"❌ Error setting up community subjects: {e}")
        raise


if __name__ == "__main__":
    setup_community_subjects()
