"""
Setup Community Subjects - Seed data for StudyHub marketplace
Creates standardized subject topics that creators can publish courses to

Run: python setup_community_subjects.py
"""

from src.database.db_manager import DBManager
from datetime import datetime
import logging

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


COMMUNITY_SUBJECTS = [
    # ==================== 💻 CÔNG NGHỆ THÔNG TIN (IT) ====================
    {
        "_id": "python-programming",
        "slug": "python-programming",
        "title": "Python Programming",
        "title_vi": "Lập trình Python",
        "description": "Learn python programming",
        "description_vi": "Học Lập trình Python",
        "category": "it",
        "icon": "🐍",
        "keywords": ["python programming", "python programming"],
        "meta_description": "Master python programming",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": True,
        "display_order": 1,
    },
    {
        "_id": "javascript-programming",
        "slug": "javascript-programming",
        "title": "JavaScript Programming",
        "title_vi": "Lập trình JavaScript",
        "description": "Learn javascript programming",
        "description_vi": "Học Lập trình JavaScript",
        "category": "it",
        "icon": "📜",
        "keywords": ["javascript programming", "javascript programming"],
        "meta_description": "Master javascript programming",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": True,
        "display_order": 2,
    },
    {
        "_id": "react-development",
        "slug": "react-development",
        "title": "React Development",
        "title_vi": "Phát triển React",
        "description": "Learn react development",
        "description_vi": "Học Phát triển React",
        "category": "it",
        "icon": "⚛️",
        "keywords": ["react development", "react development"],
        "meta_description": "Master react development",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": True,
        "display_order": 3,
    },
    {
        "_id": "nodejs-development",
        "slug": "nodejs-development",
        "title": "Node.js Development",
        "title_vi": "Phát triển Node.js",
        "description": "Learn node.js development",
        "description_vi": "Học Phát triển Node.js",
        "category": "it",
        "icon": "🟢",
        "keywords": ["nodejs development", "node.js development"],
        "meta_description": "Master node.js development",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": True,
        "display_order": 4,
    },
    {
        "_id": "web-development",
        "slug": "web-development",
        "title": "Web Development",
        "title_vi": "Phát triển Web",
        "description": "Learn web development",
        "description_vi": "Học Phát triển Web",
        "category": "it",
        "icon": "🌐",
        "keywords": ["web development", "web development"],
        "meta_description": "Master web development",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": True,
        "display_order": 5,
    },
    {
        "_id": "data-science",
        "slug": "data-science",
        "title": "Data Science",
        "title_vi": "Khoa học Dữ liệu",
        "description": "Learn data science",
        "description_vi": "Học Khoa học Dữ liệu",
        "category": "it",
        "icon": "📊",
        "keywords": ["data science", "data science"],
        "meta_description": "Master data science",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 6,
    },
    {
        "_id": "mobile-app-development",
        "slug": "mobile-app-development",
        "title": "Mobile App Development",
        "title_vi": "Phát triển Ứng dụng Di động",
        "description": "Learn mobile app development",
        "description_vi": "Học Phát triển Ứng dụng Di động",
        "category": "it",
        "icon": "📱",
        "keywords": ["mobile app development", "mobile app development"],
        "meta_description": "Master mobile app development",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 7,
    },
    {
        "_id": "database-design",
        "slug": "database-design",
        "title": "Database Design",
        "title_vi": "Thiết kế Cơ sở Dữ liệu",
        "description": "Learn database design",
        "description_vi": "Học Thiết kế Cơ sở Dữ liệu",
        "category": "it",
        "icon": "🗄️",
        "keywords": ["database design", "database design"],
        "meta_description": "Master database design",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 8,
    },
    {
        "_id": "cloud-computing",
        "slug": "cloud-computing",
        "title": "Cloud Computing",
        "title_vi": "Điện toán Đám mây",
        "description": "Learn cloud computing",
        "description_vi": "Học Điện toán Đám mây",
        "category": "it",
        "icon": "☁️",
        "keywords": ["cloud computing", "cloud computing"],
        "meta_description": "Master cloud computing",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 9,
    },
    {
        "_id": "devops",
        "slug": "devops",
        "title": "DevOps",
        "title_vi": "DevOps",
        "description": "Learn devops",
        "description_vi": "Học DevOps",
        "category": "it",
        "icon": "🔧",
        "keywords": ["devops", "devops"],
        "meta_description": "Master devops",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 10,
    },
    {
        "_id": "cybersecurity",
        "slug": "cybersecurity",
        "title": "Cybersecurity",
        "title_vi": "An ninh Mạng",
        "description": "Learn cybersecurity",
        "description_vi": "Học An ninh Mạng",
        "category": "it",
        "icon": "🔒",
        "keywords": ["cybersecurity", "cybersecurity"],
        "meta_description": "Master cybersecurity",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 11,
    },
    {
        "_id": "artificial-intelligence",
        "slug": "artificial-intelligence",
        "title": "Artificial Intelligence",
        "title_vi": "Trí tuệ Nhân tạo",
        "description": "Learn artificial intelligence",
        "description_vi": "Học Trí tuệ Nhân tạo",
        "category": "it",
        "icon": "🤖",
        "keywords": ["artificial intelligence", "artificial intelligence"],
        "meta_description": "Master artificial intelligence",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 12,
    },
    {
        "_id": "blockchain",
        "slug": "blockchain",
        "title": "Blockchain Development",
        "title_vi": "Phát triển Blockchain",
        "description": "Learn blockchain development",
        "description_vi": "Học Phát triển Blockchain",
        "category": "it",
        "icon": "⛓️",
        "keywords": ["blockchain", "blockchain development"],
        "meta_description": "Master blockchain development",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 13,
    },
    {
        "_id": "game-development",
        "slug": "game-development",
        "title": "Game Development",
        "title_vi": "Phát triển Game",
        "description": "Learn game development",
        "description_vi": "Học Phát triển Game",
        "category": "it",
        "icon": "🎮",
        "keywords": ["game development", "game development"],
        "meta_description": "Master game development",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 14,
    },
    {
        "_id": "software-testing",
        "slug": "software-testing",
        "title": "Software Testing",
        "title_vi": "Kiểm thử Phần mềm",
        "description": "Learn software testing",
        "description_vi": "Học Kiểm thử Phần mềm",
        "category": "it",
        "icon": "✅",
        "keywords": ["software testing", "software testing"],
        "meta_description": "Master software testing",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 15,
    },

    # ==================== 💼 KINH DOANH (BUSINESS) ====================
    {
        "_id": "marketing-fundamentals",
        "slug": "marketing-fundamentals",
        "title": "Marketing Fundamentals",
        "title_vi": "Cơ bản Marketing",
        "description": "Learn marketing fundamentals",
        "description_vi": "Học Cơ bản Marketing",
        "category": "business",
        "icon": "📊",
        "keywords": ["marketing fundamentals", "marketing fundamentals"],
        "meta_description": "Master marketing fundamentals",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": True,
        "display_order": 16,
    },
    {
        "_id": "digital-marketing",
        "slug": "digital-marketing",
        "title": "Digital Marketing",
        "title_vi": "Marketing Số",
        "description": "Learn digital marketing",
        "description_vi": "Học Marketing Số",
        "category": "business",
        "icon": "💻",
        "keywords": ["digital marketing", "digital marketing"],
        "meta_description": "Master digital marketing",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": True,
        "display_order": 17,
    },
    {
        "_id": "entrepreneurship",
        "slug": "entrepreneurship",
        "title": "Entrepreneurship",
        "title_vi": "Khởi nghiệp",
        "description": "Learn entrepreneurship",
        "description_vi": "Học Khởi nghiệp",
        "category": "business",
        "icon": "🚀",
        "keywords": ["entrepreneurship", "entrepreneurship"],
        "meta_description": "Master entrepreneurship",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": True,
        "display_order": 18,
    },
    {
        "_id": "project-management",
        "slug": "project-management",
        "title": "Project Management",
        "title_vi": "Quản lý Dự án",
        "description": "Learn project management",
        "description_vi": "Học Quản lý Dự án",
        "category": "business",
        "icon": "📋",
        "keywords": ["project management", "project management"],
        "meta_description": "Master project management",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": True,
        "display_order": 19,
    },
    {
        "_id": "business-strategy",
        "slug": "business-strategy",
        "title": "Business Strategy",
        "title_vi": "Chiến lược Kinh doanh",
        "description": "Learn business strategy",
        "description_vi": "Học Chiến lược Kinh doanh",
        "category": "business",
        "icon": "🎯",
        "keywords": ["business strategy", "business strategy"],
        "meta_description": "Master business strategy",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": True,
        "display_order": 20,
    },
    {
        "_id": "sales-skills",
        "slug": "sales-skills",
        "title": "Sales Skills",
        "title_vi": "Kỹ năng Bán hàng",
        "description": "Learn sales skills",
        "description_vi": "Học Kỹ năng Bán hàng",
        "category": "business",
        "icon": "💼",
        "keywords": ["sales skills", "sales skills"],
        "meta_description": "Master sales skills",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 21,
    },
    {
        "_id": "customer-service",
        "slug": "customer-service",
        "title": "Customer Service",
        "title_vi": "Dịch vụ Khách hàng",
        "description": "Learn customer service",
        "description_vi": "Học Dịch vụ Khách hàng",
        "category": "business",
        "icon": "🤝",
        "keywords": ["customer service", "customer service"],
        "meta_description": "Master customer service",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 22,
    },
    {
        "_id": "ecommerce",
        "slug": "ecommerce",
        "title": "E-Commerce",
        "title_vi": "Thương mại Điện tử",
        "description": "Learn e-commerce",
        "description_vi": "Học Thương mại Điện tử",
        "category": "business",
        "icon": "🛒",
        "keywords": ["ecommerce", "e-commerce"],
        "meta_description": "Master e-commerce",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 23,
    },
    {
        "_id": "social-media-marketing",
        "slug": "social-media-marketing",
        "title": "Social Media Marketing",
        "title_vi": "Marketing Mạng Xã hội",
        "description": "Learn social media marketing",
        "description_vi": "Học Marketing Mạng Xã hội",
        "category": "business",
        "icon": "📱",
        "keywords": ["social media marketing", "social media marketing"],
        "meta_description": "Master social media marketing",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 24,
    },
    {
        "_id": "content-marketing",
        "slug": "content-marketing",
        "title": "Content Marketing",
        "title_vi": "Marketing Nội dung",
        "description": "Learn content marketing",
        "description_vi": "Học Marketing Nội dung",
        "category": "business",
        "icon": "✍️",
        "keywords": ["content marketing", "content marketing"],
        "meta_description": "Master content marketing",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 25,
    },
    {
        "_id": "brand-management",
        "slug": "brand-management",
        "title": "Brand Management",
        "title_vi": "Quản lý Thương hiệu",
        "description": "Learn brand management",
        "description_vi": "Học Quản lý Thương hiệu",
        "category": "business",
        "icon": "🏷️",
        "keywords": ["brand management", "brand management"],
        "meta_description": "Master brand management",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 26,
    },
    {
        "_id": "business-analytics",
        "slug": "business-analytics",
        "title": "Business Analytics",
        "title_vi": "Phân tích Kinh doanh",
        "description": "Learn business analytics",
        "description_vi": "Học Phân tích Kinh doanh",
        "category": "business",
        "icon": "📈",
        "keywords": ["business analytics", "business analytics"],
        "meta_description": "Master business analytics",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 27,
    },
    {
        "_id": "supply-chain-management",
        "slug": "supply-chain-management",
        "title": "Supply Chain Management",
        "title_vi": "Quản lý Chuỗi Cung ứng",
        "description": "Learn supply chain management",
        "description_vi": "Học Quản lý Chuỗi Cung ứng",
        "category": "business",
        "icon": "🚚",
        "keywords": ["supply chain management", "supply chain management"],
        "meta_description": "Master supply chain management",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 28,
    },
    {
        "_id": "human-resources",
        "slug": "human-resources",
        "title": "Human Resources",
        "title_vi": "Quản trị Nhân sự",
        "description": "Learn human resources",
        "description_vi": "Học Quản trị Nhân sự",
        "category": "business",
        "icon": "👥",
        "keywords": ["human resources", "human resources"],
        "meta_description": "Master human resources",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 29,
    },
    {
        "_id": "leadership",
        "slug": "leadership",
        "title": "Leadership",
        "title_vi": "Kỹ năng Lãnh đạo",
        "description": "Learn leadership",
        "description_vi": "Học Kỹ năng Lãnh đạo",
        "category": "business",
        "icon": "👔",
        "keywords": ["leadership", "leadership"],
        "meta_description": "Master leadership",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 30,
    },

    # ==================== 💰 TÀI CHÍNH (FINANCE) ====================
    {
        "_id": "personal-finance",
        "slug": "personal-finance",
        "title": "Personal Finance",
        "title_vi": "Tài chính Cá nhân",
        "description": "Learn personal finance",
        "description_vi": "Học Tài chính Cá nhân",
        "category": "finance",
        "icon": "💵",
        "keywords": ["personal finance", "personal finance"],
        "meta_description": "Master personal finance",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": True,
        "display_order": 31,
    },
    {
        "_id": "investing",
        "slug": "investing",
        "title": "Investing",
        "title_vi": "Đầu tư",
        "description": "Learn investing",
        "description_vi": "Học Đầu tư",
        "category": "finance",
        "icon": "📈",
        "keywords": ["investing", "investing"],
        "meta_description": "Master investing",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": True,
        "display_order": 32,
    },
    {
        "_id": "stock-market",
        "slug": "stock-market",
        "title": "Stock Market",
        "title_vi": "Thị trường Chứng khoán",
        "description": "Learn stock market",
        "description_vi": "Học Thị trường Chứng khoán",
        "category": "finance",
        "icon": "📊",
        "keywords": ["stock market", "stock market"],
        "meta_description": "Master stock market",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": True,
        "display_order": 33,
    },
    {
        "_id": "cryptocurrency",
        "slug": "cryptocurrency",
        "title": "Cryptocurrency",
        "title_vi": "Tiền điện tử",
        "description": "Learn cryptocurrency",
        "description_vi": "Học Tiền điện tử",
        "category": "finance",
        "icon": "₿",
        "keywords": ["cryptocurrency", "cryptocurrency"],
        "meta_description": "Master cryptocurrency",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": True,
        "display_order": 34,
    },
    {
        "_id": "accounting",
        "slug": "accounting",
        "title": "Accounting",
        "title_vi": "Kế toán",
        "description": "Learn accounting",
        "description_vi": "Học Kế toán",
        "category": "finance",
        "icon": "🧮",
        "keywords": ["accounting", "accounting"],
        "meta_description": "Master accounting",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": True,
        "display_order": 35,
    },
    {
        "_id": "financial-analysis",
        "slug": "financial-analysis",
        "title": "Financial Analysis",
        "title_vi": "Phân tích Tài chính",
        "description": "Learn financial analysis",
        "description_vi": "Học Phân tích Tài chính",
        "category": "finance",
        "icon": "💹",
        "keywords": ["financial analysis", "financial analysis"],
        "meta_description": "Master financial analysis",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 36,
    },
    {
        "_id": "forex-trading",
        "slug": "forex-trading",
        "title": "Forex Trading",
        "title_vi": "Giao dịch Forex",
        "description": "Learn forex trading",
        "description_vi": "Học Giao dịch Forex",
        "category": "finance",
        "icon": "💱",
        "keywords": ["forex trading", "forex trading"],
        "meta_description": "Master forex trading",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 37,
    },
    {
        "_id": "real-estate-investing",
        "slug": "real-estate-investing",
        "title": "Real Estate Investing",
        "title_vi": "Đầu tư Bất động sản",
        "description": "Learn real estate investing",
        "description_vi": "Học Đầu tư Bất động sản",
        "category": "finance",
        "icon": "🏠",
        "keywords": ["real estate investing", "real estate investing"],
        "meta_description": "Master real estate investing",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 38,
    },
    {
        "_id": "retirement-planning",
        "slug": "retirement-planning",
        "title": "Retirement Planning",
        "title_vi": "Kế hoạch Hưu trí",
        "description": "Learn retirement planning",
        "description_vi": "Học Kế hoạch Hưu trí",
        "category": "finance",
        "icon": "🏖️",
        "keywords": ["retirement planning", "retirement planning"],
        "meta_description": "Master retirement planning",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 39,
    },
    {
        "_id": "tax-planning",
        "slug": "tax-planning",
        "title": "Tax Planning",
        "title_vi": "Kế hoạch Thuế",
        "description": "Learn tax planning",
        "description_vi": "Học Kế hoạch Thuế",
        "category": "finance",
        "icon": "📝",
        "keywords": ["tax planning", "tax planning"],
        "meta_description": "Master tax planning",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 40,
    },
    {
        "_id": "financial-modeling",
        "slug": "financial-modeling",
        "title": "Financial Modeling",
        "title_vi": "Mô hình Tài chính",
        "description": "Learn financial modeling",
        "description_vi": "Học Mô hình Tài chính",
        "category": "finance",
        "icon": "🔢",
        "keywords": ["financial modeling", "financial modeling"],
        "meta_description": "Master financial modeling",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 41,
    },
    {
        "_id": "wealth-management",
        "slug": "wealth-management",
        "title": "Wealth Management",
        "title_vi": "Quản lý Tài sản",
        "description": "Learn wealth management",
        "description_vi": "Học Quản lý Tài sản",
        "category": "finance",
        "icon": "💎",
        "keywords": ["wealth management", "wealth management"],
        "meta_description": "Master wealth management",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 42,
    },
    {
        "_id": "insurance",
        "slug": "insurance",
        "title": "Insurance",
        "title_vi": "Bảo hiểm",
        "description": "Learn insurance",
        "description_vi": "Học Bảo hiểm",
        "category": "finance",
        "icon": "🛡️",
        "keywords": ["insurance", "insurance"],
        "meta_description": "Master insurance",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 43,
    },
    {
        "_id": "banking",
        "slug": "banking",
        "title": "Banking",
        "title_vi": "Ngân hàng",
        "description": "Learn banking",
        "description_vi": "Học Ngân hàng",
        "category": "finance",
        "icon": "🏦",
        "keywords": ["banking", "banking"],
        "meta_description": "Master banking",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 44,
    },
    {
        "_id": "economics",
        "slug": "economics",
        "title": "Economics",
        "title_vi": "Kinh tế học",
        "description": "Learn economics",
        "description_vi": "Học Kinh tế học",
        "category": "finance",
        "icon": "📚",
        "keywords": ["economics", "economics"],
        "meta_description": "Master economics",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 45,
    },

    # ==================== 🎓 CHỨNG CHỈ (CERTIFICATE) ====================
    {
        "_id": "pmp-certification",
        "slug": "pmp-certification",
        "title": "PMP Certification",
        "title_vi": "Chứng chỉ PMP",
        "description": "Learn pmp certification",
        "description_vi": "Học Chứng chỉ PMP",
        "category": "certificate",
        "icon": "📜",
        "keywords": ["pmp certification", "pmp certification"],
        "meta_description": "Master pmp certification",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": True,
        "display_order": 46,
    },
    {
        "_id": "aws-certification",
        "slug": "aws-certification",
        "title": "AWS Certification",
        "title_vi": "Chứng chỉ AWS",
        "description": "Learn aws certification",
        "description_vi": "Học Chứng chỉ AWS",
        "category": "certificate",
        "icon": "☁️",
        "keywords": ["aws certification", "aws certification"],
        "meta_description": "Master aws certification",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": True,
        "display_order": 47,
    },
    {
        "_id": "google-analytics",
        "slug": "google-analytics",
        "title": "Google Analytics Certification",
        "title_vi": "Chứng chỉ Google Analytics",
        "description": "Learn google analytics certification",
        "description_vi": "Học Chứng chỉ Google Analytics",
        "category": "certificate",
        "icon": "📊",
        "keywords": ["google analytics", "google analytics certification"],
        "meta_description": "Master google analytics certification",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": True,
        "display_order": 48,
    },
    {
        "_id": "cissp",
        "slug": "cissp",
        "title": "CISSP Certification",
        "title_vi": "Chứng chỉ CISSP",
        "description": "Learn cissp certification",
        "description_vi": "Học Chứng chỉ CISSP",
        "category": "certificate",
        "icon": "🔒",
        "keywords": ["cissp", "cissp certification"],
        "meta_description": "Master cissp certification",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": True,
        "display_order": 49,
    },
    {
        "_id": "comptia",
        "slug": "comptia",
        "title": "CompTIA Certification",
        "title_vi": "Chứng chỉ CompTIA",
        "description": "Learn comptia certification",
        "description_vi": "Học Chứng chỉ CompTIA",
        "category": "certificate",
        "icon": "💻",
        "keywords": ["comptia", "comptia certification"],
        "meta_description": "Master comptia certification",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": True,
        "display_order": 50,
    },
    {
        "_id": "microsoft-certification",
        "slug": "microsoft-certification",
        "title": "Microsoft Certification",
        "title_vi": "Chứng chỉ Microsoft",
        "description": "Learn microsoft certification",
        "description_vi": "Học Chứng chỉ Microsoft",
        "category": "certificate",
        "icon": "🪟",
        "keywords": ["microsoft certification", "microsoft certification"],
        "meta_description": "Master microsoft certification",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 51,
    },
    {
        "_id": "scrum-master",
        "slug": "scrum-master",
        "title": "Scrum Master Certification",
        "title_vi": "Chứng chỉ Scrum Master",
        "description": "Learn scrum master certification",
        "description_vi": "Học Chứng chỉ Scrum Master",
        "category": "certificate",
        "icon": "🏃",
        "keywords": ["scrum master", "scrum master certification"],
        "meta_description": "Master scrum master certification",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 52,
    },
    {
        "_id": "six-sigma",
        "slug": "six-sigma",
        "title": "Six Sigma Certification",
        "title_vi": "Chứng chỉ Six Sigma",
        "description": "Learn six sigma certification",
        "description_vi": "Học Chứng chỉ Six Sigma",
        "category": "certificate",
        "icon": "📈",
        "keywords": ["six sigma", "six sigma certification"],
        "meta_description": "Master six sigma certification",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 53,
    },
    {
        "_id": "cpa",
        "slug": "cpa",
        "title": "CPA Certification",
        "title_vi": "Chứng chỉ CPA",
        "description": "Learn cpa certification",
        "description_vi": "Học Chứng chỉ CPA",
        "category": "certificate",
        "icon": "🧮",
        "keywords": ["cpa", "cpa certification"],
        "meta_description": "Master cpa certification",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 54,
    },
    {
        "_id": "cfa",
        "slug": "cfa",
        "title": "CFA Certification",
        "title_vi": "Chứng chỉ CFA",
        "description": "Learn cfa certification",
        "description_vi": "Học Chứng chỉ CFA",
        "category": "certificate",
        "icon": "📊",
        "keywords": ["cfa", "cfa certification"],
        "meta_description": "Master cfa certification",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 55,
    },
    {
        "_id": "itil",
        "slug": "itil",
        "title": "ITIL Certification",
        "title_vi": "Chứng chỉ ITIL",
        "description": "Learn itil certification",
        "description_vi": "Học Chứng chỉ ITIL",
        "category": "certificate",
        "icon": "🔧",
        "keywords": ["itil", "itil certification"],
        "meta_description": "Master itil certification",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 56,
    },
    {
        "_id": "cisco",
        "slug": "cisco",
        "title": "Cisco Certification",
        "title_vi": "Chứng chỉ Cisco",
        "description": "Learn cisco certification",
        "description_vi": "Học Chứng chỉ Cisco",
        "category": "certificate",
        "icon": "🌐",
        "keywords": ["cisco", "cisco certification"],
        "meta_description": "Master cisco certification",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 57,
    },
    {
        "_id": "oracle-certification",
        "slug": "oracle-certification",
        "title": "Oracle Certification",
        "title_vi": "Chứng chỉ Oracle",
        "description": "Learn oracle certification",
        "description_vi": "Học Chứng chỉ Oracle",
        "category": "certificate",
        "icon": "🗄️",
        "keywords": ["oracle certification", "oracle certification"],
        "meta_description": "Master oracle certification",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 58,
    },
    {
        "_id": "google-cloud",
        "slug": "google-cloud",
        "title": "Google Cloud Certification",
        "title_vi": "Chứng chỉ Google Cloud",
        "description": "Learn google cloud certification",
        "description_vi": "Học Chứng chỉ Google Cloud",
        "category": "certificate",
        "icon": "☁️",
        "keywords": ["google cloud", "google cloud certification"],
        "meta_description": "Master google cloud certification",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 59,
    },
    {
        "_id": "azure-certification",
        "slug": "azure-certification",
        "title": "Azure Certification",
        "title_vi": "Chứng chỉ Azure",
        "description": "Learn azure certification",
        "description_vi": "Học Chứng chỉ Azure",
        "category": "certificate",
        "icon": "🔷",
        "keywords": ["azure certification", "azure certification"],
        "meta_description": "Master azure certification",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 60,
    },

    # ==================== 🌍 NGÔN NGỮ (LANGUAGE) ====================
    {
        "_id": "english-speaking",
        "slug": "english-speaking",
        "title": "English Speaking",
        "title_vi": "Giao tiếp Tiếng Anh",
        "description": "Learn english speaking",
        "description_vi": "Học Giao tiếp Tiếng Anh",
        "category": "language",
        "icon": "🗣️",
        "keywords": ["english speaking", "english speaking"],
        "meta_description": "Master english speaking",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": True,
        "display_order": 61,
    },
    {
        "_id": "ielts-preparation",
        "slug": "ielts-preparation",
        "title": "IELTS Preparation",
        "title_vi": "Luyện thi IELTS",
        "description": "Learn ielts preparation",
        "description_vi": "Học Luyện thi IELTS",
        "category": "language",
        "icon": "📚",
        "keywords": ["ielts preparation", "ielts preparation"],
        "meta_description": "Master ielts preparation",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": True,
        "display_order": 62,
    },
    {
        "_id": "toeic-preparation",
        "slug": "toeic-preparation",
        "title": "TOEIC Preparation",
        "title_vi": "Luyện thi TOEIC",
        "description": "Learn toeic preparation",
        "description_vi": "Học Luyện thi TOEIC",
        "category": "language",
        "icon": "📝",
        "keywords": ["toeic preparation", "toeic preparation"],
        "meta_description": "Master toeic preparation",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": True,
        "display_order": 63,
    },
    {
        "_id": "toefl-preparation",
        "slug": "toefl-preparation",
        "title": "TOEFL Preparation",
        "title_vi": "Luyện thi TOEFL",
        "description": "Learn toefl preparation",
        "description_vi": "Học Luyện thi TOEFL",
        "category": "language",
        "icon": "📖",
        "keywords": ["toefl preparation", "toefl preparation"],
        "meta_description": "Master toefl preparation",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": True,
        "display_order": 64,
    },
    {
        "_id": "chinese-language",
        "slug": "chinese-language",
        "title": "Chinese Language",
        "title_vi": "Tiếng Trung",
        "description": "Learn chinese language",
        "description_vi": "Học Tiếng Trung",
        "category": "language",
        "icon": "🇨🇳",
        "keywords": ["chinese language", "chinese language"],
        "meta_description": "Master chinese language",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": True,
        "display_order": 65,
    },
    {
        "_id": "japanese-language",
        "slug": "japanese-language",
        "title": "Japanese Language",
        "title_vi": "Tiếng Nhật",
        "description": "Learn japanese language",
        "description_vi": "Học Tiếng Nhật",
        "category": "language",
        "icon": "🇯🇵",
        "keywords": ["japanese language", "japanese language"],
        "meta_description": "Master japanese language",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 66,
    },
    {
        "_id": "korean-language",
        "slug": "korean-language",
        "title": "Korean Language",
        "title_vi": "Tiếng Hàn",
        "description": "Learn korean language",
        "description_vi": "Học Tiếng Hàn",
        "category": "language",
        "icon": "🇰🇷",
        "keywords": ["korean language", "korean language"],
        "meta_description": "Master korean language",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 67,
    },
    {
        "_id": "french-language",
        "slug": "french-language",
        "title": "French Language",
        "title_vi": "Tiếng Pháp",
        "description": "Learn french language",
        "description_vi": "Học Tiếng Pháp",
        "category": "language",
        "icon": "🇫🇷",
        "keywords": ["french language", "french language"],
        "meta_description": "Master french language",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 68,
    },
    {
        "_id": "german-language",
        "slug": "german-language",
        "title": "German Language",
        "title_vi": "Tiếng Đức",
        "description": "Learn german language",
        "description_vi": "Học Tiếng Đức",
        "category": "language",
        "icon": "🇩🇪",
        "keywords": ["german language", "german language"],
        "meta_description": "Master german language",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 69,
    },
    {
        "_id": "spanish-language",
        "slug": "spanish-language",
        "title": "Spanish Language",
        "title_vi": "Tiếng Tây Ban Nha",
        "description": "Learn spanish language",
        "description_vi": "Học Tiếng Tây Ban Nha",
        "category": "language",
        "icon": "🇪🇸",
        "keywords": ["spanish language", "spanish language"],
        "meta_description": "Master spanish language",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 70,
    },
    {
        "_id": "english-grammar",
        "slug": "english-grammar",
        "title": "English Grammar",
        "title_vi": "Ngữ pháp Tiếng Anh",
        "description": "Learn english grammar",
        "description_vi": "Học Ngữ pháp Tiếng Anh",
        "category": "language",
        "icon": "📖",
        "keywords": ["english grammar", "english grammar"],
        "meta_description": "Master english grammar",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 71,
    },
    {
        "_id": "business-english",
        "slug": "business-english",
        "title": "Business English",
        "title_vi": "Tiếng Anh Thương mại",
        "description": "Learn business english",
        "description_vi": "Học Tiếng Anh Thương mại",
        "category": "language",
        "icon": "💼",
        "keywords": ["business english", "business english"],
        "meta_description": "Master business english",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 72,
    },
    {
        "_id": "english-writing",
        "slug": "english-writing",
        "title": "English Writing",
        "title_vi": "Viết Tiếng Anh",
        "description": "Learn english writing",
        "description_vi": "Học Viết Tiếng Anh",
        "category": "language",
        "icon": "✍️",
        "keywords": ["english writing", "english writing"],
        "meta_description": "Master english writing",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 73,
    },
    {
        "_id": "pronunciation",
        "slug": "pronunciation",
        "title": "Pronunciation",
        "title_vi": "Phát âm",
        "description": "Learn pronunciation",
        "description_vi": "Học Phát âm",
        "category": "language",
        "icon": "🎤",
        "keywords": ["pronunciation", "pronunciation"],
        "meta_description": "Master pronunciation",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 74,
    },
    {
        "_id": "vocabulary-building",
        "slug": "vocabulary-building",
        "title": "Vocabulary Building",
        "title_vi": "Xây dựng Từ vựng",
        "description": "Learn vocabulary building",
        "description_vi": "Học Xây dựng Từ vựng",
        "category": "language",
        "icon": "📚",
        "keywords": ["vocabulary building", "vocabulary building"],
        "meta_description": "Master vocabulary building",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 75,
    },

    # ==================== 🌱 PHÁT TRIỂN BẢN THÂN (PERSONAL DEVELOPMENT) ====================
    {
        "_id": "time-management",
        "slug": "time-management",
        "title": "Time Management",
        "title_vi": "Quản lý Thời gian",
        "description": "Learn time management",
        "description_vi": "Học Quản lý Thời gian",
        "category": "personal-development",
        "icon": "⏰",
        "keywords": ["time management", "time management"],
        "meta_description": "Master time management",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": True,
        "display_order": 76,
    },
    {
        "_id": "productivity",
        "slug": "productivity",
        "title": "Productivity",
        "title_vi": "Năng suất",
        "description": "Learn productivity",
        "description_vi": "Học Năng suất",
        "category": "personal-development",
        "icon": "⚡",
        "keywords": ["productivity", "productivity"],
        "meta_description": "Master productivity",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": True,
        "display_order": 77,
    },
    {
        "_id": "goal-setting",
        "slug": "goal-setting",
        "title": "Goal Setting",
        "title_vi": "Đặt mục tiêu",
        "description": "Learn goal setting",
        "description_vi": "Học Đặt mục tiêu",
        "category": "personal-development",
        "icon": "🎯",
        "keywords": ["goal setting", "goal setting"],
        "meta_description": "Master goal setting",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": True,
        "display_order": 78,
    },
    {
        "_id": "mindfulness",
        "slug": "mindfulness",
        "title": "Mindfulness",
        "title_vi": "Chánh niệm",
        "description": "Learn mindfulness",
        "description_vi": "Học Chánh niệm",
        "category": "personal-development",
        "icon": "🧘",
        "keywords": ["mindfulness", "mindfulness"],
        "meta_description": "Master mindfulness",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": True,
        "display_order": 79,
    },
    {
        "_id": "meditation",
        "slug": "meditation",
        "title": "Meditation",
        "title_vi": "Thiền",
        "description": "Learn meditation",
        "description_vi": "Học Thiền",
        "category": "personal-development",
        "icon": "🧘‍♂️",
        "keywords": ["meditation", "meditation"],
        "meta_description": "Master meditation",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": True,
        "display_order": 80,
    },
    {
        "_id": "public-speaking",
        "slug": "public-speaking",
        "title": "Public Speaking",
        "title_vi": "Nói trước Công chúng",
        "description": "Learn public speaking",
        "description_vi": "Học Nói trước Công chúng",
        "category": "personal-development",
        "icon": "🎤",
        "keywords": ["public speaking", "public speaking"],
        "meta_description": "Master public speaking",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 81,
    },
    {
        "_id": "confidence-building",
        "slug": "confidence-building",
        "title": "Confidence Building",
        "title_vi": "Xây dựng Tự tin",
        "description": "Learn confidence building",
        "description_vi": "Học Xây dựng Tự tin",
        "category": "personal-development",
        "icon": "💪",
        "keywords": ["confidence building", "confidence building"],
        "meta_description": "Master confidence building",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 82,
    },
    {
        "_id": "critical-thinking",
        "slug": "critical-thinking",
        "title": "Critical Thinking",
        "title_vi": "Tư duy Phản biện",
        "description": "Learn critical thinking",
        "description_vi": "Học Tư duy Phản biện",
        "category": "personal-development",
        "icon": "🤔",
        "keywords": ["critical thinking", "critical thinking"],
        "meta_description": "Master critical thinking",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 83,
    },
    {
        "_id": "emotional-intelligence",
        "slug": "emotional-intelligence",
        "title": "Emotional Intelligence",
        "title_vi": "Trí tuệ Cảm xúc",
        "description": "Learn emotional intelligence",
        "description_vi": "Học Trí tuệ Cảm xúc",
        "category": "personal-development",
        "icon": "❤️",
        "keywords": ["emotional intelligence", "emotional intelligence"],
        "meta_description": "Master emotional intelligence",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 84,
    },
    {
        "_id": "stress-management",
        "slug": "stress-management",
        "title": "Stress Management",
        "title_vi": "Quản lý Căng thẳng",
        "description": "Learn stress management",
        "description_vi": "Học Quản lý Căng thẳng",
        "category": "personal-development",
        "icon": "😌",
        "keywords": ["stress management", "stress management"],
        "meta_description": "Master stress management",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 85,
    },
    {
        "_id": "memory-improvement",
        "slug": "memory-improvement",
        "title": "Memory Improvement",
        "title_vi": "Cải thiện Trí nhớ",
        "description": "Learn memory improvement",
        "description_vi": "Học Cải thiện Trí nhớ",
        "category": "personal-development",
        "icon": "🧠",
        "keywords": ["memory improvement", "memory improvement"],
        "meta_description": "Master memory improvement",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 86,
    },
    {
        "_id": "speed-reading",
        "slug": "speed-reading",
        "title": "Speed Reading",
        "title_vi": "Đọc nhanh",
        "description": "Learn speed reading",
        "description_vi": "Học Đọc nhanh",
        "category": "personal-development",
        "icon": "📖",
        "keywords": ["speed reading", "speed reading"],
        "meta_description": "Master speed reading",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 87,
    },
    {
        "_id": "creativity",
        "slug": "creativity",
        "title": "Creativity",
        "title_vi": "Sáng tạo",
        "description": "Learn creativity",
        "description_vi": "Học Sáng tạo",
        "category": "personal-development",
        "icon": "💡",
        "keywords": ["creativity", "creativity"],
        "meta_description": "Master creativity",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 88,
    },
    {
        "_id": "motivation",
        "slug": "motivation",
        "title": "Motivation",
        "title_vi": "Động lực",
        "description": "Learn motivation",
        "description_vi": "Học Động lực",
        "category": "personal-development",
        "icon": "🔥",
        "keywords": ["motivation", "motivation"],
        "meta_description": "Master motivation",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 89,
    },
    {
        "_id": "self-discipline",
        "slug": "self-discipline",
        "title": "Self-Discipline",
        "title_vi": "Kỷ luật Bản thân",
        "description": "Learn self-discipline",
        "description_vi": "Học Kỷ luật Bản thân",
        "category": "personal-development",
        "icon": "🎖️",
        "keywords": ["self discipline", "self-discipline"],
        "meta_description": "Master self-discipline",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 90,
    },

    # ==================== 🎨 LỐI SỐNG (LIFESTYLE) ====================
    {
        "_id": "graphic-design",
        "slug": "graphic-design",
        "title": "Graphic Design",
        "title_vi": "Thiết kế Đồ họa",
        "description": "Learn graphic design",
        "description_vi": "Học Thiết kế Đồ họa",
        "category": "lifestyle",
        "icon": "🎨",
        "keywords": ["graphic design", "graphic design"],
        "meta_description": "Master graphic design",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": True,
        "display_order": 91,
    },
    {
        "_id": "photography",
        "slug": "photography",
        "title": "Photography",
        "title_vi": "Nhiếp ảnh",
        "description": "Learn photography",
        "description_vi": "Học Nhiếp ảnh",
        "category": "lifestyle",
        "icon": "📷",
        "keywords": ["photography", "photography"],
        "meta_description": "Master photography",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": True,
        "display_order": 92,
    },
    {
        "_id": "video-editing",
        "slug": "video-editing",
        "title": "Video Editing",
        "title_vi": "Dựng Video",
        "description": "Learn video editing",
        "description_vi": "Học Dựng Video",
        "category": "lifestyle",
        "icon": "🎬",
        "keywords": ["video editing", "video editing"],
        "meta_description": "Master video editing",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": True,
        "display_order": 93,
    },
    {
        "_id": "music-production",
        "slug": "music-production",
        "title": "Music Production",
        "title_vi": "Sản xuất Âm nhạc",
        "description": "Learn music production",
        "description_vi": "Học Sản xuất Âm nhạc",
        "category": "lifestyle",
        "icon": "🎵",
        "keywords": ["music production", "music production"],
        "meta_description": "Master music production",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": True,
        "display_order": 94,
    },
    {
        "_id": "cooking",
        "slug": "cooking",
        "title": "Cooking",
        "title_vi": "Nấu ăn",
        "description": "Learn cooking",
        "description_vi": "Học Nấu ăn",
        "category": "lifestyle",
        "icon": "🍳",
        "keywords": ["cooking", "cooking"],
        "meta_description": "Master cooking",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": True,
        "display_order": 95,
    },
    {
        "_id": "fitness",
        "slug": "fitness",
        "title": "Fitness",
        "title_vi": "Thể dục",
        "description": "Learn fitness",
        "description_vi": "Học Thể dục",
        "category": "lifestyle",
        "icon": "💪",
        "keywords": ["fitness", "fitness"],
        "meta_description": "Master fitness",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 96,
    },
    {
        "_id": "yoga",
        "slug": "yoga",
        "title": "Yoga",
        "title_vi": "Yoga",
        "description": "Learn yoga",
        "description_vi": "Học Yoga",
        "category": "lifestyle",
        "icon": "🧘",
        "keywords": ["yoga", "yoga"],
        "meta_description": "Master yoga",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 97,
    },
    {
        "_id": "nutrition",
        "slug": "nutrition",
        "title": "Nutrition",
        "title_vi": "Dinh dưỡng",
        "description": "Learn nutrition",
        "description_vi": "Học Dinh dưỡng",
        "category": "lifestyle",
        "icon": "🥗",
        "keywords": ["nutrition", "nutrition"],
        "meta_description": "Master nutrition",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 98,
    },
    {
        "_id": "interior-design",
        "slug": "interior-design",
        "title": "Interior Design",
        "title_vi": "Thiết kế Nội thất",
        "description": "Learn interior design",
        "description_vi": "Học Thiết kế Nội thất",
        "category": "lifestyle",
        "icon": "🏠",
        "keywords": ["interior design", "interior design"],
        "meta_description": "Master interior design",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 99,
    },
    {
        "_id": "fashion-design",
        "slug": "fashion-design",
        "title": "Fashion Design",
        "title_vi": "Thiết kế Thời trang",
        "description": "Learn fashion design",
        "description_vi": "Học Thiết kế Thời trang",
        "category": "lifestyle",
        "icon": "👗",
        "keywords": ["fashion design", "fashion design"],
        "meta_description": "Master fashion design",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 100,
    },
    {
        "_id": "gardening",
        "slug": "gardening",
        "title": "Gardening",
        "title_vi": "Làm vườn",
        "description": "Learn gardening",
        "description_vi": "Học Làm vườn",
        "category": "lifestyle",
        "icon": "🌱",
        "keywords": ["gardening", "gardening"],
        "meta_description": "Master gardening",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 101,
    },
    {
        "_id": "travel-planning",
        "slug": "travel-planning",
        "title": "Travel Planning",
        "title_vi": "Lập kế hoạch Du lịch",
        "description": "Learn travel planning",
        "description_vi": "Học Lập kế hoạch Du lịch",
        "category": "lifestyle",
        "icon": "✈️",
        "keywords": ["travel planning", "travel planning"],
        "meta_description": "Master travel planning",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 102,
    },
    {
        "_id": "pet-care",
        "slug": "pet-care",
        "title": "Pet Care",
        "title_vi": "Chăm sóc Thú cưng",
        "description": "Learn pet care",
        "description_vi": "Học Chăm sóc Thú cưng",
        "category": "lifestyle",
        "icon": "🐕",
        "keywords": ["pet care", "pet care"],
        "meta_description": "Master pet care",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 103,
    },
    {
        "_id": "home-organization",
        "slug": "home-organization",
        "title": "Home Organization",
        "title_vi": "Tổ chức Nhà cửa",
        "description": "Learn home organization",
        "description_vi": "Học Tổ chức Nhà cửa",
        "category": "lifestyle",
        "icon": "🏡",
        "keywords": ["home organization", "home organization"],
        "meta_description": "Master home organization",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 104,
    },
    {
        "_id": "sustainable-living",
        "slug": "sustainable-living",
        "title": "Sustainable Living",
        "title_vi": "Sống Bền vững",
        "description": "Learn sustainable living",
        "description_vi": "Học Sống Bền vững",
        "category": "lifestyle",
        "icon": "♻️",
        "keywords": ["sustainable living", "sustainable living"],
        "meta_description": "Master sustainable living",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 105,
    },

    # ==================== 📚 HỌC THUẬT (ACADEMICS) ====================
    {
        "_id": "toan-12",
        "slug": "toan-12",
        "title": "Toán 12",
        "title_vi": "Toán học lớp 12",
        "description": "Learn toán 12",
        "description_vi": "Học Toán học lớp 12",
        "category": "academics",
        "icon": "📐",
        "keywords": ["toan 12", "toán 12"],
        "meta_description": "Master toán 12",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": True,
        "display_order": 106,
    },
    {
        "_id": "vat-ly-12",
        "slug": "vat-ly-12",
        "title": "Vật lý 12",
        "title_vi": "Vật lý lớp 12",
        "description": "Learn vật lý 12",
        "description_vi": "Học Vật lý lớp 12",
        "category": "academics",
        "icon": "⚗️",
        "keywords": ["vat ly 12", "vật lý 12"],
        "meta_description": "Master vật lý 12",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": True,
        "display_order": 107,
    },
    {
        "_id": "hoa-hoc-12",
        "slug": "hoa-hoc-12",
        "title": "Hóa học 12",
        "title_vi": "Hóa học lớp 12",
        "description": "Learn hóa học 12",
        "description_vi": "Học Hóa học lớp 12",
        "category": "academics",
        "icon": "🧪",
        "keywords": ["hoa hoc 12", "hóa học 12"],
        "meta_description": "Master hóa học 12",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": True,
        "display_order": 108,
    },
    {
        "_id": "tieng-anh-12",
        "slug": "tieng-anh-12",
        "title": "Tiếng Anh 12",
        "title_vi": "Tiếng Anh lớp 12",
        "description": "Learn tiếng anh 12",
        "description_vi": "Học Tiếng Anh lớp 12",
        "category": "academics",
        "icon": "🇬🇧",
        "keywords": ["tieng anh 12", "tiếng anh 12"],
        "meta_description": "Master tiếng anh 12",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": True,
        "display_order": 109,
    },
    {
        "_id": "van-hoc-12",
        "slug": "van-hoc-12",
        "title": "Văn học 12",
        "title_vi": "Văn học lớp 12",
        "description": "Learn văn học 12",
        "description_vi": "Học Văn học lớp 12",
        "category": "academics",
        "icon": "📖",
        "keywords": ["van hoc 12", "văn học 12"],
        "meta_description": "Master văn học 12",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": True,
        "display_order": 110,
    },
    {
        "_id": "lich-su-12",
        "slug": "lich-su-12",
        "title": "Lịch sử 12",
        "title_vi": "Lịch sử lớp 12",
        "description": "Learn lịch sử 12",
        "description_vi": "Học Lịch sử lớp 12",
        "category": "academics",
        "icon": "📜",
        "keywords": ["lich su 12", "lịch sử 12"],
        "meta_description": "Master lịch sử 12",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 111,
    },
    {
        "_id": "dia-ly-12",
        "slug": "dia-ly-12",
        "title": "Địa lý 12",
        "title_vi": "Địa lý lớp 12",
        "description": "Learn địa lý 12",
        "description_vi": "Học Địa lý lớp 12",
        "category": "academics",
        "icon": "🌍",
        "keywords": ["dia ly 12", "địa lý 12"],
        "meta_description": "Master địa lý 12",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 112,
    },
    {
        "_id": "sinh-hoc-12",
        "slug": "sinh-hoc-12",
        "title": "Sinh học 12",
        "title_vi": "Sinh học lớp 12",
        "description": "Learn sinh học 12",
        "description_vi": "Học Sinh học lớp 12",
        "category": "academics",
        "icon": "🔬",
        "keywords": ["sinh hoc 12", "sinh học 12"],
        "meta_description": "Master sinh học 12",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 113,
    },
    {
        "_id": "gdcd-12",
        "slug": "gdcd-12",
        "title": "GDCD 12",
        "title_vi": "Giáo dục Công dân lớp 12",
        "description": "Learn gdcd 12",
        "description_vi": "Học Giáo dục Công dân lớp 12",
        "category": "academics",
        "icon": "⚖️",
        "keywords": ["gdcd 12", "gdcd 12"],
        "meta_description": "Master gdcd 12",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 114,
    },
    {
        "_id": "sat-preparation",
        "slug": "sat-preparation",
        "title": "SAT Preparation",
        "title_vi": "Luyện thi SAT",
        "description": "Learn sat preparation",
        "description_vi": "Học Luyện thi SAT",
        "category": "academics",
        "icon": "📝",
        "keywords": ["sat preparation", "sat preparation"],
        "meta_description": "Master sat preparation",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 115,
    },
    {
        "_id": "act-preparation",
        "slug": "act-preparation",
        "title": "ACT Preparation",
        "title_vi": "Luyện thi ACT",
        "description": "Learn act preparation",
        "description_vi": "Học Luyện thi ACT",
        "category": "academics",
        "icon": "📚",
        "keywords": ["act preparation", "act preparation"],
        "meta_description": "Master act preparation",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 116,
    },
    {
        "_id": "gre-preparation",
        "slug": "gre-preparation",
        "title": "GRE Preparation",
        "title_vi": "Luyện thi GRE",
        "description": "Learn gre preparation",
        "description_vi": "Học Luyện thi GRE",
        "category": "academics",
        "icon": "🎓",
        "keywords": ["gre preparation", "gre preparation"],
        "meta_description": "Master gre preparation",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 117,
    },
    {
        "_id": "gmat-preparation",
        "slug": "gmat-preparation",
        "title": "GMAT Preparation",
        "title_vi": "Luyện thi GMAT",
        "description": "Learn gmat preparation",
        "description_vi": "Học Luyện thi GMAT",
        "category": "academics",
        "icon": "📊",
        "keywords": ["gmat preparation", "gmat preparation"],
        "meta_description": "Master gmat preparation",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 118,
    },
    {
        "_id": "college-admission",
        "slug": "college-admission",
        "title": "College Admission",
        "title_vi": "Tuyển sinh Đại học",
        "description": "Learn college admission",
        "description_vi": "Học Tuyển sinh Đại học",
        "category": "academics",
        "icon": "🏫",
        "keywords": ["college admission", "college admission"],
        "meta_description": "Master college admission",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 119,
    },
    {
        "_id": "essay-writing",
        "slug": "essay-writing",
        "title": "Essay Writing",
        "title_vi": "Viết Luận",
        "description": "Learn essay writing",
        "description_vi": "Học Viết Luận",
        "category": "academics",
        "icon": "✍️",
        "keywords": ["essay writing", "essay writing"],
        "meta_description": "Master essay writing",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 120,
    },

    # ==================== 🔬 KHOA HỌC (SCIENCE) ====================
    {
        "_id": "physics",
        "slug": "physics",
        "title": "Physics",
        "title_vi": "Vật lý",
        "description": "Learn physics",
        "description_vi": "Học Vật lý",
        "category": "science",
        "icon": "⚛️",
        "keywords": ["physics", "physics"],
        "meta_description": "Master physics",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": True,
        "display_order": 121,
    },
    {
        "_id": "chemistry",
        "slug": "chemistry",
        "title": "Chemistry",
        "title_vi": "Hóa học",
        "description": "Learn chemistry",
        "description_vi": "Học Hóa học",
        "category": "science",
        "icon": "🧪",
        "keywords": ["chemistry", "chemistry"],
        "meta_description": "Master chemistry",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": True,
        "display_order": 122,
    },
    {
        "_id": "biology",
        "slug": "biology",
        "title": "Biology",
        "title_vi": "Sinh học",
        "description": "Learn biology",
        "description_vi": "Học Sinh học",
        "category": "science",
        "icon": "🔬",
        "keywords": ["biology", "biology"],
        "meta_description": "Master biology",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": True,
        "display_order": 123,
    },
    {
        "_id": "astronomy",
        "slug": "astronomy",
        "title": "Astronomy",
        "title_vi": "Thiên văn học",
        "description": "Learn astronomy",
        "description_vi": "Học Thiên văn học",
        "category": "science",
        "icon": "🌌",
        "keywords": ["astronomy", "astronomy"],
        "meta_description": "Master astronomy",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": True,
        "display_order": 124,
    },
    {
        "_id": "geology",
        "slug": "geology",
        "title": "Geology",
        "title_vi": "Địa chất học",
        "description": "Learn geology",
        "description_vi": "Học Địa chất học",
        "category": "science",
        "icon": "🪨",
        "keywords": ["geology", "geology"],
        "meta_description": "Master geology",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": True,
        "display_order": 125,
    },
    {
        "_id": "environmental-science",
        "slug": "environmental-science",
        "title": "Environmental Science",
        "title_vi": "Khoa học Môi trường",
        "description": "Learn environmental science",
        "description_vi": "Học Khoa học Môi trường",
        "category": "science",
        "icon": "🌍",
        "keywords": ["environmental science", "environmental science"],
        "meta_description": "Master environmental science",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 126,
    },
    {
        "_id": "marine-biology",
        "slug": "marine-biology",
        "title": "Marine Biology",
        "title_vi": "Sinh học Biển",
        "description": "Learn marine biology",
        "description_vi": "Học Sinh học Biển",
        "category": "science",
        "icon": "🌊",
        "keywords": ["marine biology", "marine biology"],
        "meta_description": "Master marine biology",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 127,
    },
    {
        "_id": "botany",
        "slug": "botany",
        "title": "Botany",
        "title_vi": "Thực vật học",
        "description": "Learn botany",
        "description_vi": "Học Thực vật học",
        "category": "science",
        "icon": "🌿",
        "keywords": ["botany", "botany"],
        "meta_description": "Master botany",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 128,
    },
    {
        "_id": "zoology",
        "slug": "zoology",
        "title": "Zoology",
        "title_vi": "Động vật học",
        "description": "Learn zoology",
        "description_vi": "Học Động vật học",
        "category": "science",
        "icon": "🦁",
        "keywords": ["zoology", "zoology"],
        "meta_description": "Master zoology",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 129,
    },
    {
        "_id": "genetics",
        "slug": "genetics",
        "title": "Genetics",
        "title_vi": "Di truyền học",
        "description": "Learn genetics",
        "description_vi": "Học Di truyền học",
        "category": "science",
        "icon": "🧬",
        "keywords": ["genetics", "genetics"],
        "meta_description": "Master genetics",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 130,
    },
    {
        "_id": "neuroscience",
        "slug": "neuroscience",
        "title": "Neuroscience",
        "title_vi": "Khoa học Thần kinh",
        "description": "Learn neuroscience",
        "description_vi": "Học Khoa học Thần kinh",
        "category": "science",
        "icon": "🧠",
        "keywords": ["neuroscience", "neuroscience"],
        "meta_description": "Master neuroscience",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 131,
    },
    {
        "_id": "psychology",
        "slug": "psychology",
        "title": "Psychology",
        "title_vi": "Tâm lý học",
        "description": "Learn psychology",
        "description_vi": "Học Tâm lý học",
        "category": "science",
        "icon": "🧠",
        "keywords": ["psychology", "psychology"],
        "meta_description": "Master psychology",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 132,
    },
    {
        "_id": "anatomy",
        "slug": "anatomy",
        "title": "Anatomy",
        "title_vi": "Giải phẫu học",
        "description": "Learn anatomy",
        "description_vi": "Học Giải phẫu học",
        "category": "science",
        "icon": "🫁",
        "keywords": ["anatomy", "anatomy"],
        "meta_description": "Master anatomy",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 133,
    },
    {
        "_id": "microbiology",
        "slug": "microbiology",
        "title": "Microbiology",
        "title_vi": "Vi sinh vật học",
        "description": "Learn microbiology",
        "description_vi": "Học Vi sinh vật học",
        "category": "science",
        "icon": "🦠",
        "keywords": ["microbiology", "microbiology"],
        "meta_description": "Master microbiology",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 134,
    },
    {
        "_id": "biochemistry",
        "slug": "biochemistry",
        "title": "Biochemistry",
        "title_vi": "Hóa sinh",
        "description": "Learn biochemistry",
        "description_vi": "Học Hóa sinh",
        "category": "science",
        "icon": "⚗️",
        "keywords": ["biochemistry", "biochemistry"],
        "meta_description": "Master biochemistry",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 135,
    },

    # ==================== 🛠️ KỸ NĂNG (SKILLS) ====================
    {
        "_id": "excel-skills",
        "slug": "excel-skills",
        "title": "Excel Skills",
        "title_vi": "Kỹ năng Excel",
        "description": "Learn excel skills",
        "description_vi": "Học Kỹ năng Excel",
        "category": "skills",
        "icon": "📊",
        "keywords": ["excel skills", "excel skills"],
        "meta_description": "Master excel skills",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": True,
        "display_order": 136,
    },
    {
        "_id": "powerpoint",
        "slug": "powerpoint",
        "title": "PowerPoint",
        "title_vi": "PowerPoint",
        "description": "Learn powerpoint",
        "description_vi": "Học PowerPoint",
        "category": "skills",
        "icon": "📽️",
        "keywords": ["powerpoint", "powerpoint"],
        "meta_description": "Master powerpoint",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": True,
        "display_order": 137,
    },
    {
        "_id": "word-processing",
        "slug": "word-processing",
        "title": "Word Processing",
        "title_vi": "Soạn thảo Văn bản",
        "description": "Learn word processing",
        "description_vi": "Học Soạn thảo Văn bản",
        "category": "skills",
        "icon": "📝",
        "keywords": ["word processing", "word processing"],
        "meta_description": "Master word processing",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": True,
        "display_order": 138,
    },
    {
        "_id": "typing-speed",
        "slug": "typing-speed",
        "title": "Typing Speed",
        "title_vi": "Tốc độ Đánh máy",
        "description": "Learn typing speed",
        "description_vi": "Học Tốc độ Đánh máy",
        "category": "skills",
        "icon": "⌨️",
        "keywords": ["typing speed", "typing speed"],
        "meta_description": "Master typing speed",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": True,
        "display_order": 139,
    },
    {
        "_id": "data-entry",
        "slug": "data-entry",
        "title": "Data Entry",
        "title_vi": "Nhập liệu",
        "description": "Learn data entry",
        "description_vi": "Học Nhập liệu",
        "category": "skills",
        "icon": "💻",
        "keywords": ["data entry", "data entry"],
        "meta_description": "Master data entry",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": True,
        "display_order": 140,
    },
    {
        "_id": "customer-support",
        "slug": "customer-support",
        "title": "Customer Support",
        "title_vi": "Hỗ trợ Khách hàng",
        "description": "Learn customer support",
        "description_vi": "Học Hỗ trợ Khách hàng",
        "category": "skills",
        "icon": "🎧",
        "keywords": ["customer support", "customer support"],
        "meta_description": "Master customer support",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 141,
    },
    {
        "_id": "negotiation",
        "slug": "negotiation",
        "title": "Negotiation",
        "title_vi": "Đàm phán",
        "description": "Learn negotiation",
        "description_vi": "Học Đàm phán",
        "category": "skills",
        "icon": "🤝",
        "keywords": ["negotiation", "negotiation"],
        "meta_description": "Master negotiation",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 142,
    },
    {
        "_id": "conflict-resolution",
        "slug": "conflict-resolution",
        "title": "Conflict Resolution",
        "title_vi": "Giải quyết Xung đột",
        "description": "Learn conflict resolution",
        "description_vi": "Học Giải quyết Xung đột",
        "category": "skills",
        "icon": "⚖️",
        "keywords": ["conflict resolution", "conflict resolution"],
        "meta_description": "Master conflict resolution",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 143,
    },
    {
        "_id": "teamwork",
        "slug": "teamwork",
        "title": "Teamwork",
        "title_vi": "Làm việc Nhóm",
        "description": "Learn teamwork",
        "description_vi": "Học Làm việc Nhóm",
        "category": "skills",
        "icon": "👥",
        "keywords": ["teamwork", "teamwork"],
        "meta_description": "Master teamwork",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 144,
    },
    {
        "_id": "problem-solving",
        "slug": "problem-solving",
        "title": "Problem Solving",
        "title_vi": "Giải quyết Vấn đề",
        "description": "Learn problem solving",
        "description_vi": "Học Giải quyết Vấn đề",
        "category": "skills",
        "icon": "🧩",
        "keywords": ["problem solving", "problem solving"],
        "meta_description": "Master problem solving",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 145,
    },
    {
        "_id": "decision-making",
        "slug": "decision-making",
        "title": "Decision Making",
        "title_vi": "Ra quyết định",
        "description": "Learn decision making",
        "description_vi": "Học Ra quyết định",
        "category": "skills",
        "icon": "🎯",
        "keywords": ["decision making", "decision making"],
        "meta_description": "Master decision making",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 146,
    },
    {
        "_id": "networking",
        "slug": "networking",
        "title": "Networking",
        "title_vi": "Xây dựng Mạng lưới",
        "description": "Learn networking",
        "description_vi": "Học Xây dựng Mạng lưới",
        "category": "skills",
        "icon": "🌐",
        "keywords": ["networking", "networking"],
        "meta_description": "Master networking",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 147,
    },
    {
        "_id": "communication-skills",
        "slug": "communication-skills",
        "title": "Communication Skills",
        "title_vi": "Kỹ năng Giao tiếp",
        "description": "Learn communication skills",
        "description_vi": "Học Kỹ năng Giao tiếp",
        "category": "skills",
        "icon": "💬",
        "keywords": ["communication skills", "communication skills"],
        "meta_description": "Master communication skills",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 148,
    },
    {
        "_id": "presentation-skills",
        "slug": "presentation-skills",
        "title": "Presentation Skills",
        "title_vi": "Kỹ năng Thuyết trình",
        "description": "Learn presentation skills",
        "description_vi": "Học Kỹ năng Thuyết trình",
        "category": "skills",
        "icon": "🎤",
        "keywords": ["presentation skills", "presentation skills"],
        "meta_description": "Master presentation skills",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 149,
    },
    {
        "_id": "writing-skills",
        "slug": "writing-skills",
        "title": "Writing Skills",
        "title_vi": "Kỹ năng Viết",
        "description": "Learn writing skills",
        "description_vi": "Học Kỹ năng Viết",
        "category": "skills",
        "icon": "✍️",
        "keywords": ["writing skills", "writing skills"],
        "meta_description": "Master writing skills",
        "total_courses": 0,
        "total_students": 0,
        "avg_rating": 0.0,
        "is_featured": False,
        "display_order": 150,
    },

]


def setup_community_subjects():
    """Seed community subjects collection"""
    try:
        db_manager = DBManager()
        db = db_manager.db
        collection = db["community_subjects"]

        # Add timestamps
        now = datetime.utcnow()
        for subject in COMMUNITY_SUBJECTS:
            subject["created_at"] = now
            subject["updated_at"] = now

        # Drop existing collection (if re-seeding)
        collection.drop()
        logger.info("Dropped existing community_subjects collection")

        # Insert subjects
        result = collection.insert_many(COMMUNITY_SUBJECTS)
        logger.info(f"✅ Inserted {len(result.inserted_ids)} community subjects")

        # Create indexes
        logger.info("Creating indexes...")
        collection.create_index([("slug", 1)], unique=True)
        collection.create_index([("category", 1)])
        collection.create_index([("title", "text"), ("title_vi", "text")])
        collection.create_index([("total_courses", -1)])
        collection.create_index([("total_students", -1)])
        collection.create_index([("is_featured", -1), ("display_order", 1)])
        logger.info("✅ Created indexes for community_subjects")

        # Print summary
        logger.info("\n" + "=" * 60)
        logger.info("SUMMARY BY CATEGORY:")
        logger.info("=" * 60)
        categories = ["it", "business", "finance", "certificate", "language",
                     "personal-development", "lifestyle", "academics", "science", "skills"]
        for cat in categories:
            count = len([s for s in COMMUNITY_SUBJECTS if s["category"] == cat])
            logger.info(f"  {cat.upper()}: {count} subjects")

        logger.info("\n✅ Community subjects setup completed!")
        logger.info(f"Total subjects: {len(COMMUNITY_SUBJECTS)}")

    except Exception as e:
        logger.error(f"❌ Error setting up community subjects: {e}")
        raise


if __name__ == "__main__":
    setup_community_subjects()
